remote_theme : old-jekyll-templates/Strata-Jekyll-Theme

locale: "en-US"
title: YUJIN's Algorithm Study # Title of your site
url: "https://yujiny97.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: ""

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  알고리즘 스터디 홈페이지 입니다.

# Author details for the jekyll-seo-tag gem
author:
  name: YuJinLee
  email: i5533m@naver.com
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: YUJIN's github
  links:
    - https://github.com/yujiny97/yujiny97.github.io

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
